import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1756558374658 implements MigrationInterface {
    name = 'InitMigration1756558374658'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid, "name" character varying(255) NOT NULL, "description" text, "isSystem" boolean NOT NULL DEFAULT false, "permissions" jsonb NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, CONSTRAINT "UQ_d27a5e69fb41256abed347a85eb" UNIQUE ("organizationId", "name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0933e1dfb2993d672af1a98f08" ON "roles" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" uuid NOT NULL, "roleId" uuid NOT NULL, "grantedBy" uuid, "grantedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "role_id" uuid, "granted_by" uuid, CONSTRAINT "PK_88481b0c4ed9ada47e9fdd67475" PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "userId" uuid NOT NULL, "name" character varying(255) NOT NULL, "keyHash" character varying(255) NOT NULL, "lastUsedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "scopes" jsonb NOT NULL DEFAULT '[]', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "user_id" uuid, CONSTRAINT "UQ_df3b25181df0b4b59bd93f16e10" UNIQUE ("keyHash"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df3b25181df0b4b59bd93f16e1" ON "api_keys" ("keyHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c2e267ae764a9413b863a2934" ON "api_keys" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1888b4544f52d274e98f6f1aa6" ON "api_keys" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "prd" text, "status" character varying(50) NOT NULL DEFAULT 'planning', "requirements" jsonb NOT NULL DEFAULT '[]', "milestones" jsonb NOT NULL DEFAULT '[]', "metadata" jsonb NOT NULL DEFAULT '{}', "createdById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "created_by" uuid, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f55144dc92df43cd1dad5d29b9" ON "projects" ("createdById") `);
        await queryRunner.query(`CREATE INDEX "IDX_a27865a7be17886e3088f4a650" ON "projects" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_eec93fd979bdcf5a0141da324d" ON "projects" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "task_executions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "taskId" uuid NOT NULL, "agentId" uuid, "status" character varying(50) NOT NULL, "startedAt" TIMESTAMP NOT NULL DEFAULT now(), "completedAt" TIMESTAMP, "durationMs" integer, "result" jsonb, "error" text, "tokensUsed" integer, "cost" numeric(10,4), "metadata" jsonb NOT NULL DEFAULT '{}', "task_id" uuid, "agent_id" uuid, CONSTRAINT "PK_c7eaf7e1f306ae5b1938e759152" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ad8ed169891a49126b4c85bec" ON "task_executions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7098f5765b2330dfe292cbaa30" ON "task_executions" ("agentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_313cf125e389752f88bcf8b9f3" ON "task_executions" ("taskId") `);
        await queryRunner.query(`CREATE TABLE "agent_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agentId" uuid NOT NULL, "date" date NOT NULL, "tasksCompleted" integer NOT NULL DEFAULT '0', "tasksFailed" integer NOT NULL DEFAULT '0', "totalDurationMs" bigint NOT NULL DEFAULT '0', "totalTokensUsed" bigint NOT NULL DEFAULT '0', "totalCost" numeric(10,4) NOT NULL DEFAULT '0', "successRate" double precision, "avgDurationMs" integer, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "agent_id" uuid, CONSTRAINT "UQ_e0d535c71e9a27b328cf5cd403c" UNIQUE ("agentId", "date"), CONSTRAINT "PK_bacac16f2d0c796a41cf4d0cee5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f54f48bf8b6b8e97eece82221" ON "agent_metrics" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f7c0c1be646a627bda0ed7b54" ON "agent_metrics" ("agentId") `);
        await queryRunner.query(`CREATE TABLE "agents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agentId" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "type" character varying(50) NOT NULL, "provider" character varying(100) NOT NULL, "version" character varying(50), "endpoint" character varying(500), "capabilities" jsonb NOT NULL DEFAULT '[]', "maxConcurrentTasks" integer NOT NULL DEFAULT '1', "timeoutMs" integer NOT NULL DEFAULT '300000', "costConfig" jsonb NOT NULL DEFAULT '{}', "metadata" jsonb NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_49c61d9abe4282f87c1593c0d0a" UNIQUE ("agentId"), CONSTRAINT "PK_9c653f28ae19c5884d5baf6a1d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e6128e1703932e8fc36883dab" ON "agents" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_32c54ef6dfe79a69e352ac481c" ON "agents" ("provider") `);
        await queryRunner.query(`CREATE TABLE "collaboration_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "taskId" uuid NOT NULL, "strategy" character varying(50) NOT NULL, "agents" uuid array NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'active', "results" jsonb NOT NULL DEFAULT '[]', "metadata" jsonb NOT NULL DEFAULT '{}', "startedAt" TIMESTAMP NOT NULL DEFAULT now(), "completedAt" TIMESTAMP, "task_id" uuid, CONSTRAINT "PK_161c36edc6ac54f8cb7b6d070c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81820b002a75265ac3e9dce3f6" ON "collaboration_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0e181844e4e80cb5482d573d1" ON "collaboration_sessions" ("taskId") `);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "projectId" uuid, "parentTaskId" uuid, "type" character varying(50) NOT NULL DEFAULT 'implementation', "title" character varying(500) NOT NULL, "description" text, "status" character varying(50) NOT NULL DEFAULT 'pending', "priority" character varying(20) NOT NULL DEFAULT 'medium', "assignedAgentId" uuid, "dependencies" uuid array NOT NULL DEFAULT '{}', "requirements" jsonb NOT NULL DEFAULT '[]', "input" jsonb NOT NULL DEFAULT '{}', "output" jsonb, "error" text, "estimatedDuration" integer, "actualDuration" integer, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "metadata" jsonb NOT NULL DEFAULT '{}', "createdById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "project_id" uuid, "parent_task_id" uuid, "assigned_agent" uuid, "created_by" uuid, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_660898d912c6e71107e9ef8f38" ON "tasks" ("createdById") `);
        await queryRunner.query(`CREATE INDEX "IDX_d69529ba3aad91898cd420175c" ON "tasks" ("assignedAgentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6086c8dafbae729a930c04d865" ON "tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e08fca67ca8966e6b9914bf295" ON "tasks" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9a5a9fada64fc56e2aaf2f946" ON "tasks" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "userId" uuid, "action" character varying(100) NOT NULL, "resourceType" character varying(100) NOT NULL, "resourceId" uuid, "changes" jsonb NOT NULL DEFAULT '{}', "ipAddress" inet, "userAgent" text, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "user_id" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e229d453b21312155c6ab8cfd" ON "audit_logs" ("resourceType", "resourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d031e6155834882f54dcd6b4f" ON "audit_logs" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid, "email" character varying(255) NOT NULL, "username" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "firstName" character varying(255) NOT NULL, "lastName" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastLogin" TIMESTAMP, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3d6aea8fcca58182b2e80ce97" ON "users" ("organizationId") `);
        await queryRunner.query(`CREATE TYPE "public"."webhook_events_event_type_enum" AS ENUM('push', 'pull_request', 'issues', 'release', 'tag_push', 'wiki', 'pipeline', 'deployment')`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_events_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "webhook_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "repository_integration_id" character varying NOT NULL, "organization_id" character varying NOT NULL, "event_type" "public"."webhook_events_event_type_enum" NOT NULL, "repository_name" character varying NOT NULL, "repository_id" character varying NOT NULL, "webhook_delivery_id" character varying, "event_action" character varying, "event_data" jsonb NOT NULL, "status" "public"."webhook_events_status_enum" NOT NULL DEFAULT 'pending', "processing_started_at" TIMESTAMP, "processing_completed_at" TIMESTAMP, "processing_duration_ms" integer, "processing_results" jsonb, "error_message" character varying, "error_stack" character varying, "retry_count" integer NOT NULL DEFAULT '0', "max_retries" integer NOT NULL DEFAULT '3', "next_retry_at" TIMESTAMP, "received_at" TIMESTAMP NOT NULL, "signature_verified" boolean NOT NULL DEFAULT false, "raw_headers" jsonb, "raw_payload_hash" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "repositoryIntegrationId" uuid, "organizationId" uuid, CONSTRAINT "PK_4cba37e6a0acb5e1fc49c34ebfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e96d7cc3c0ed14e6574ef574cf" ON "webhook_events" ("repository_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_8cb477890137f5551422e00a60" ON "webhook_events" ("received_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3ebad0c6b2075ee5c33f7d172" ON "webhook_events" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_99c9011566b175ab79b0a1e174" ON "webhook_events" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_de96a1b4d6ff1fe4ca1c260bb6" ON "webhook_events" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5bcfb29c7b0b5eeed008ce6c28" ON "webhook_events" ("repository_integration_id") `);
        await queryRunner.query(`CREATE TYPE "public"."automation_executions_triggered_by_enum" AS ENUM('webhook', 'schedule', 'manual', 'api')`);
        await queryRunner.query(`CREATE TYPE "public"."automation_executions_status_enum" AS ENUM('pending', 'running', 'completed', 'failed', 'cancelled', 'timeout')`);
        await queryRunner.query(`CREATE TABLE "automation_executions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "automation_rule_id" character varying NOT NULL, "organization_id" character varying NOT NULL, "repository_integration_id" character varying, "webhook_event_id" character varying, "repository_name" character varying NOT NULL, "event_type" character varying, "event_action" character varying, "triggered_by" "public"."automation_executions_triggered_by_enum" NOT NULL, "execution_context" jsonb NOT NULL, "event_data" jsonb, "status" "public"."automation_executions_status_enum" NOT NULL DEFAULT 'pending', "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "duration_ms" integer, "execution_results" jsonb, "execution_metrics" jsonb, "error_message" character varying, "error_stack" character varying, "error_code" character varying, "retry_count" integer NOT NULL DEFAULT '0', "max_retries" integer NOT NULL DEFAULT '0', "next_retry_at" TIMESTAMP, "timeout_seconds" integer, "progress_percentage" integer NOT NULL DEFAULT '0', "current_step" character varying, "total_steps" integer, "logs" text, "execution_node" character varying, "execution_version" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "automationRuleId" uuid, "organizationId" uuid, "repositoryIntegrationId" uuid, "webhookEventId" uuid, CONSTRAINT "PK_dc450e9c9835c88bb3d5abec4c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_265171e460963d1d034463c8e2" ON "automation_executions" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d5c228370015815048cf9b577" ON "automation_executions" ("repository_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_93696255a30e9089e86f699837" ON "automation_executions" ("started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b32bc5980b6ce47cbe54a1bb15" ON "automation_executions" ("triggered_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8ee929f447738de0a61af2973" ON "automation_executions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b47a26a072b145b96ca698e6c1" ON "automation_executions" ("repository_integration_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d78cb413d2cd354c4692f45726" ON "automation_executions" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_12fd5cf50fadb34d9f5dcdb941" ON "automation_executions" ("automation_rule_id") `);
        await queryRunner.query(`CREATE TABLE "automation_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "repository_integration_id" character varying, "name" character varying NOT NULL, "description" text NOT NULL, "repository_pattern" character varying NOT NULL DEFAULT '.*', "rule_type" character varying NOT NULL DEFAULT 'event_triggered', "enabled" boolean NOT NULL DEFAULT true, "triggers" jsonb NOT NULL, "actions" jsonb NOT NULL, "execution_order" integer NOT NULL DEFAULT '0', "max_executions_per_hour" integer, "max_executions_per_day" integer, "cooldown_minutes" integer NOT NULL DEFAULT '0', "last_executed_at" TIMESTAMP, "execution_count" integer NOT NULL DEFAULT '0', "success_count" integer NOT NULL DEFAULT '0', "failure_count" integer NOT NULL DEFAULT '0', "average_execution_time_ms" integer, "is_template" boolean NOT NULL DEFAULT false, "template_category" character varying, "created_by_user_id" character varying, "updated_by_user_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "organizationId" uuid, "repositoryIntegrationId" uuid, CONSTRAINT "PK_378bed501eacc036895837121c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b8f0ac9eb1ee5fa90fd104c55" ON "automation_rules" ("repository_pattern") `);
        await queryRunner.query(`CREATE INDEX "IDX_27035bc8bf044bccb2ed850db1" ON "automation_rules" ("rule_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e9a12f0a7310ee8f20428475f" ON "automation_rules" ("enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_7907111500c89477cf55d0c69f" ON "automation_rules" ("repository_integration_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5e0046a155be651786b22a879" ON "automation_rules" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."repository_integrations_provider_enum" AS ENUM('github', 'gitlab')`);
        await queryRunner.query(`CREATE TABLE "repository_integrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" character varying NOT NULL, "repository_id" character varying NOT NULL, "repository_name" character varying NOT NULL, "repository_url" character varying, "repository_description" character varying, "provider" "public"."repository_integrations_provider_enum" NOT NULL DEFAULT 'github', "webhook_url" character varying, "webhook_id" character varying, "auto_create_tasks" boolean NOT NULL DEFAULT false, "auto_create_pr" boolean NOT NULL DEFAULT false, "branch_prefix" character varying, "default_branch" character varying NOT NULL DEFAULT 'main', "settings" jsonb NOT NULL DEFAULT '{"enabledEvents": ["push", "pull_request", "issues"], "taskCreationRules": {}}', "last_sync_at" TIMESTAMP, "sync_status" character varying NOT NULL DEFAULT 'pending', "sync_error" character varying, "is_active" boolean NOT NULL DEFAULT true, "access_token_encrypted" character varying, "access_token_expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "organizationId" uuid, CONSTRAINT "PK_ab22c0aebb416cc271bd88d548c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f81c096ac8dd1db0d3bf501673" ON "repository_integrations" ("repository_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5922ef592f521ee9f61a69927" ON "repository_integrations" ("provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1a5f46588ef8e5b3db7b21521" ON "repository_integrations" ("repository_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c071cf08cfe5bb1b66f5f8c980" ON "repository_integrations" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "settings" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_963693341bd612aa01ddf3a4b68" UNIQUE ("slug"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "approval_responses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "approvalRequestId" uuid NOT NULL, "approverId" uuid NOT NULL, "decision" character varying(20) NOT NULL, "comment" text, "respondedAt" TIMESTAMP NOT NULL DEFAULT now(), "approval_request_id" uuid, "approver_id" uuid, CONSTRAINT "PK_18d248713b01275263246614c84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f0d4a69918f166edbaa4030eed" ON "approval_responses" ("approverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77cd8cb7e0d07e550f82b3c618" ON "approval_responses" ("approvalRequestId") `);
        await queryRunner.query(`CREATE TABLE "approval_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "workflowExecutionId" uuid, "workflowStepId" character varying(255), "stepName" character varying(255), "workflowName" character varying(255), "requestedById" uuid, "approvers" uuid array NOT NULL, "policy" character varying(50) NOT NULL DEFAULT 'all', "minApprovals" integer NOT NULL DEFAULT '1', "status" character varying(50) NOT NULL DEFAULT 'pending', "timeoutAt" TIMESTAMP, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "workflow_execution_id" uuid, "requested_by" uuid, CONSTRAINT "PK_484806bb8ff331b851fc75973c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40474ff19c594757c811a1343c" ON "approval_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8bda3b778fc23fbfb73195922" ON "approval_requests" ("workflowExecutionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f45df3f8c6cb9dc8b6573e2c2" ON "approval_requests" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "workflow_executions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflowId" uuid NOT NULL, "status" character varying(50) NOT NULL, "variables" jsonb NOT NULL DEFAULT '{}', "currentStep" character varying(255), "results" jsonb NOT NULL DEFAULT '{}', "error" text, "startedAt" TIMESTAMP NOT NULL DEFAULT now(), "completedAt" TIMESTAMP, "triggeredById" uuid, "workflow_id" uuid, "triggered_by" uuid, CONSTRAINT "PK_9d49b5c86c267d902145ed42c9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a7ec594219eeb8c58b7c615c7" ON "workflow_executions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cb399c231cb3f82c63506794b" ON "workflow_executions" ("workflowId") `);
        await queryRunner.query(`CREATE TABLE "workflows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "definition" jsonb NOT NULL, "variables" jsonb NOT NULL DEFAULT '{}', "triggers" jsonb NOT NULL DEFAULT '[]', "isActive" boolean NOT NULL DEFAULT true, "createdById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "created_by" uuid, CONSTRAINT "PK_5b5757cc1cd86268019fef52e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a89c3eb9c7266815698b86048" ON "workflows" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5b97c3123140983764e48265f" ON "workflows" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "category" character varying(100), "definition" jsonb NOT NULL, "variables" jsonb NOT NULL DEFAULT '{}', "tags" text array NOT NULL DEFAULT '{}', "isPublic" boolean NOT NULL DEFAULT false, "createdById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "created_by" uuid, CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_568ff7d00e30d6e3b436bbd68d" ON "templates" ("isPublic") `);
        await queryRunner.query(`CREATE INDEX "IDX_db04a72eab7a66358ca87e6cc4" ON "templates" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b7c8e48218dfe6fce78ea8ebe" ON "templates" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "knowledge_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "type" character varying(50) NOT NULL, "category" character varying(100), "title" character varying(500) NOT NULL, "content" text, "embedding" double precision array, "metadata" jsonb NOT NULL DEFAULT '{}', "source" character varying(255), "confidenceScore" double precision NOT NULL DEFAULT '1', "usageCount" integer NOT NULL DEFAULT '0', "lastAccessed" TIMESTAMP, "createdById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organization_id" uuid, "created_by" uuid, CONSTRAINT "PK_5c344c4dc5439f5679927ad1f40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_503cb7841c71ac3fbdcf5f1d8a" ON "knowledge_entries" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7d737eb2eb893124df35f9e3f" ON "knowledge_entries" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_a065b7523a39e731d64b933763" ON "knowledge_entries" ("organizationId") `);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_5d2beedacbe986e0dbabba67a84" FOREIGN KEY ("granted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_a283bdef18876e525aefaec042f" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_585c8ce06628c70b70100bfb842" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_executions" ADD CONSTRAINT "FK_5b81d3bcbd7c22af221d03ffb1e" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_executions" ADD CONSTRAINT "FK_d42efeca0234f2121aa8b623542" FOREIGN KEY ("agent_id") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent_metrics" ADD CONSTRAINT "FK_c5a2ee5fd961ee1504171c2695a" FOREIGN KEY ("agent_id") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collaboration_sessions" ADD CONSTRAINT "FK_e9bf2ade6e5f19428ffe2ef9dd1" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_44a9b5209cdfd6f72fb09a7c994" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_54fc42a253a8338488ec1f960ad" FOREIGN KEY ("parent_task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_6aefdce7258036e7019db9e54e0" FOREIGN KEY ("assigned_agent") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_145f35b204c731ba7fc1a0be0e7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_21a659804ed7bf61eb91688dea7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD CONSTRAINT "FK_ead069e74e8a81c777479c19cb1" FOREIGN KEY ("repositoryIntegrationId") REFERENCES "repository_integrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD CONSTRAINT "FK_56b42e2dcaa8fe719e05fe7a202" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_executions" ADD CONSTRAINT "FK_b40c75cfbb56a2c8bbe112d2da3" FOREIGN KEY ("automationRuleId") REFERENCES "automation_rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_executions" ADD CONSTRAINT "FK_fd6419a4ecb71d2a9c36dcd58e5" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_executions" ADD CONSTRAINT "FK_d1830535ed3f2ce1ab3be9e7e8b" FOREIGN KEY ("repositoryIntegrationId") REFERENCES "repository_integrations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_executions" ADD CONSTRAINT "FK_36234db8700becd5601c1157aac" FOREIGN KEY ("webhookEventId") REFERENCES "webhook_events"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_rules" ADD CONSTRAINT "FK_7a25182d0c92b05b9635c9b42b6" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_rules" ADD CONSTRAINT "FK_d2ecdea37a0897a15e8f9554ec1" FOREIGN KEY ("repositoryIntegrationId") REFERENCES "repository_integrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repository_integrations" ADD CONSTRAINT "FK_c837fd75377f152d316eed641f2" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_responses" ADD CONSTRAINT "FK_ae064328209bdd6e2df0766b8dc" FOREIGN KEY ("approval_request_id") REFERENCES "approval_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_responses" ADD CONSTRAINT "FK_d323d50aaea579ea184e1b578d9" FOREIGN KEY ("approver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_requests" ADD CONSTRAINT "FK_48206c45316b368509fa89b7bac" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_requests" ADD CONSTRAINT "FK_ad861fce1b95943d323d4c61ed0" FOREIGN KEY ("workflow_execution_id") REFERENCES "workflow_executions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_requests" ADD CONSTRAINT "FK_0bcfff2aed6c93f6fa089720b36" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_executions" ADD CONSTRAINT "FK_6347f114eeaac28722f959f6e3f" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_executions" ADD CONSTRAINT "FK_40be3ecd1434057cbe3605fe9b9" FOREIGN KEY ("triggered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflows" ADD CONSTRAINT "FK_d0327b3752cf21c97fb7ae9f0b2" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflows" ADD CONSTRAINT "FK_5d7e754199da9d7bf87f810ff17" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "templates" ADD CONSTRAINT "FK_e1a4d8ae904ce011b0a81a089a1" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "templates" ADD CONSTRAINT "FK_e0753fa8d20f4eae08ebec1fef9" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_entries" ADD CONSTRAINT "FK_ef7c2ed55af628258193e8d889c" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_entries" ADD CONSTRAINT "FK_422101fc3c0f7a44b37fd4bc143" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "knowledge_entries" DROP CONSTRAINT "FK_422101fc3c0f7a44b37fd4bc143"`);
        await queryRunner.query(`ALTER TABLE "knowledge_entries" DROP CONSTRAINT "FK_ef7c2ed55af628258193e8d889c"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP CONSTRAINT "FK_e0753fa8d20f4eae08ebec1fef9"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP CONSTRAINT "FK_e1a4d8ae904ce011b0a81a089a1"`);
        await queryRunner.query(`ALTER TABLE "workflows" DROP CONSTRAINT "FK_5d7e754199da9d7bf87f810ff17"`);
        await queryRunner.query(`ALTER TABLE "workflows" DROP CONSTRAINT "FK_d0327b3752cf21c97fb7ae9f0b2"`);
        await queryRunner.query(`ALTER TABLE "workflow_executions" DROP CONSTRAINT "FK_40be3ecd1434057cbe3605fe9b9"`);
        await queryRunner.query(`ALTER TABLE "workflow_executions" DROP CONSTRAINT "FK_6347f114eeaac28722f959f6e3f"`);
        await queryRunner.query(`ALTER TABLE "approval_requests" DROP CONSTRAINT "FK_0bcfff2aed6c93f6fa089720b36"`);
        await queryRunner.query(`ALTER TABLE "approval_requests" DROP CONSTRAINT "FK_ad861fce1b95943d323d4c61ed0"`);
        await queryRunner.query(`ALTER TABLE "approval_requests" DROP CONSTRAINT "FK_48206c45316b368509fa89b7bac"`);
        await queryRunner.query(`ALTER TABLE "approval_responses" DROP CONSTRAINT "FK_d323d50aaea579ea184e1b578d9"`);
        await queryRunner.query(`ALTER TABLE "approval_responses" DROP CONSTRAINT "FK_ae064328209bdd6e2df0766b8dc"`);
        await queryRunner.query(`ALTER TABLE "repository_integrations" DROP CONSTRAINT "FK_c837fd75377f152d316eed641f2"`);
        await queryRunner.query(`ALTER TABLE "automation_rules" DROP CONSTRAINT "FK_d2ecdea37a0897a15e8f9554ec1"`);
        await queryRunner.query(`ALTER TABLE "automation_rules" DROP CONSTRAINT "FK_7a25182d0c92b05b9635c9b42b6"`);
        await queryRunner.query(`ALTER TABLE "automation_executions" DROP CONSTRAINT "FK_36234db8700becd5601c1157aac"`);
        await queryRunner.query(`ALTER TABLE "automation_executions" DROP CONSTRAINT "FK_d1830535ed3f2ce1ab3be9e7e8b"`);
        await queryRunner.query(`ALTER TABLE "automation_executions" DROP CONSTRAINT "FK_fd6419a4ecb71d2a9c36dcd58e5"`);
        await queryRunner.query(`ALTER TABLE "automation_executions" DROP CONSTRAINT "FK_b40c75cfbb56a2c8bbe112d2da3"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP CONSTRAINT "FK_56b42e2dcaa8fe719e05fe7a202"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP CONSTRAINT "FK_ead069e74e8a81c777479c19cb1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_21a659804ed7bf61eb91688dea7"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_145f35b204c731ba7fc1a0be0e7"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_6aefdce7258036e7019db9e54e0"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_54fc42a253a8338488ec1f960ad"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_44a9b5209cdfd6f72fb09a7c994"`);
        await queryRunner.query(`ALTER TABLE "collaboration_sessions" DROP CONSTRAINT "FK_e9bf2ade6e5f19428ffe2ef9dd1"`);
        await queryRunner.query(`ALTER TABLE "agent_metrics" DROP CONSTRAINT "FK_c5a2ee5fd961ee1504171c2695a"`);
        await queryRunner.query(`ALTER TABLE "task_executions" DROP CONSTRAINT "FK_d42efeca0234f2121aa8b623542"`);
        await queryRunner.query(`ALTER TABLE "task_executions" DROP CONSTRAINT "FK_5b81d3bcbd7c22af221d03ffb1e"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_585c8ce06628c70b70100bfb842"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a283bdef18876e525aefaec042f"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_5d2beedacbe986e0dbabba67a84"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a065b7523a39e731d64b933763"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7d737eb2eb893124df35f9e3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_503cb7841c71ac3fbdcf5f1d8a"`);
        await queryRunner.query(`DROP TABLE "knowledge_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b7c8e48218dfe6fce78ea8ebe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db04a72eab7a66358ca87e6cc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_568ff7d00e30d6e3b436bbd68d"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5b97c3123140983764e48265f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a89c3eb9c7266815698b86048"`);
        await queryRunner.query(`DROP TABLE "workflows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cb399c231cb3f82c63506794b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a7ec594219eeb8c58b7c615c7"`);
        await queryRunner.query(`DROP TABLE "workflow_executions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f45df3f8c6cb9dc8b6573e2c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8bda3b778fc23fbfb73195922"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40474ff19c594757c811a1343c"`);
        await queryRunner.query(`DROP TABLE "approval_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77cd8cb7e0d07e550f82b3c618"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0d4a69918f166edbaa4030eed"`);
        await queryRunner.query(`DROP TABLE "approval_responses"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c071cf08cfe5bb1b66f5f8c980"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1a5f46588ef8e5b3db7b21521"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5922ef592f521ee9f61a69927"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f81c096ac8dd1db0d3bf501673"`);
        await queryRunner.query(`DROP TABLE "repository_integrations"`);
        await queryRunner.query(`DROP TYPE "public"."repository_integrations_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5e0046a155be651786b22a879"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7907111500c89477cf55d0c69f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e9a12f0a7310ee8f20428475f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27035bc8bf044bccb2ed850db1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b8f0ac9eb1ee5fa90fd104c55"`);
        await queryRunner.query(`DROP TABLE "automation_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12fd5cf50fadb34d9f5dcdb941"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d78cb413d2cd354c4692f45726"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b47a26a072b145b96ca698e6c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8ee929f447738de0a61af2973"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b32bc5980b6ce47cbe54a1bb15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93696255a30e9089e86f699837"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d5c228370015815048cf9b577"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_265171e460963d1d034463c8e2"`);
        await queryRunner.query(`DROP TABLE "automation_executions"`);
        await queryRunner.query(`DROP TYPE "public"."automation_executions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."automation_executions_triggered_by_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bcfb29c7b0b5eeed008ce6c28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de96a1b4d6ff1fe4ca1c260bb6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99c9011566b175ab79b0a1e174"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3ebad0c6b2075ee5c33f7d172"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cb477890137f5551422e00a60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e96d7cc3c0ed14e6574ef574cf"`);
        await queryRunner.query(`DROP TABLE "webhook_events"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_events_event_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3d6aea8fcca58182b2e80ce97"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d031e6155834882f54dcd6b4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e229d453b21312155c6ab8cfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9a5a9fada64fc56e2aaf2f946"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e08fca67ca8966e6b9914bf295"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6086c8dafbae729a930c04d865"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d69529ba3aad91898cd420175c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_660898d912c6e71107e9ef8f38"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0e181844e4e80cb5482d573d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81820b002a75265ac3e9dce3f6"`);
        await queryRunner.query(`DROP TABLE "collaboration_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32c54ef6dfe79a69e352ac481c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e6128e1703932e8fc36883dab"`);
        await queryRunner.query(`DROP TABLE "agents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f7c0c1be646a627bda0ed7b54"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f54f48bf8b6b8e97eece82221"`);
        await queryRunner.query(`DROP TABLE "agent_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_313cf125e389752f88bcf8b9f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7098f5765b2330dfe292cbaa30"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ad8ed169891a49126b4c85bec"`);
        await queryRunner.query(`DROP TABLE "task_executions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eec93fd979bdcf5a0141da324d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a27865a7be17886e3088f4a650"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f55144dc92df43cd1dad5d29b9"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1888b4544f52d274e98f6f1aa6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c2e267ae764a9413b863a2934"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df3b25181df0b4b59bd93f16e1"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0933e1dfb2993d672af1a98f08"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
